name: Java HelloWorld action
run-name: ${{ github.actor }} has tested helloWorld in java
on: [push]
jobs:
  hello-world:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - run: javac HelloWorld.java
      - run: java HelloWorld
  
  deployment:
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - run: echo "done"
